###
# @description Password authentication
# @name passwordLogin
POST {{BASE_URL}}/auth/password/login
Content-Type: application/json

{
  "email": "teo@oniryk.dev",
  "password": "secret"
}


###
# @description Send a password reset email
POST {{BASE_URL}}/auth/password/forgot
Content-Type: application/json

{
  "email": "teo@oniryk.dev",
}

### 
# @description Reset password
@code = {{$input Password reset code $value: code}}
@password = {{$input New password $value: secret}}
POST {{BASE_URL}}/auth/password/reset
Content-Type: application/json

{
  "code": "{{ code }}",
  "password": "{{ password }}"
}
