import db from './connector';
import schemaInspector from 'knex-schema-inspector';
import fs from 'node:fs';
import path from 'node:path';

const inspector = schemaInspector(db);

async function getTableSchema() {
  const tables = (await inspector.tables()).filter((table) => !table.startsWith('knex'));
  const dumpFile = path.join(__dirname, 'tables.d.ts');
  const columns: Record<string, string[]> = {};

  for (const table of tables) {
    const tableColumns = await inspector.columns(table);
    columns[table] = tableColumns.map(({ column }) => column);
    console.log(tableColumns);
  }

  const code = Object.keys(columns).reduce((acc, table) => {
    const types = columns[table].map((column) => `'${column}'`).join(' | ');
    return `${acc}\n  ${table}: ${types};`;
  }, '');

  fs.writeFileSync(
    dumpFile,
    `
// This file is auto-generated by running "npm run db:dump-types"
// Do not edit this file directly

export type DatabaseMap = {${code}
};
`
  );

  db.destroy();
}

getTableSchema();
